name: Deploy to Firebase
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checks out your repo

      - name: Verify files        # Debugging step
        run: ls -la               # Lists files to confirm package.json exists

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install          # Runs in root by default

      - name: Build
        run: npm run build        # Your build command

      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
